### PR TITLE
New option "label"

### PR DESCRIPTION
**Pull request by richvoronov**
Hi!
I am sure this option will be useful because everyone use `label` for `input` tag.

Now you can add `label` tag.

```
  <ModernDatepicker
    label="Date"
    id="dateId"
    date={this.state.startDate}
    format={'DD-MM-YYYY'}
    onChange={(date) => this.handleChange(date)}
  />
``` 

NOTE: don't forget to specify `id` for the `ModernDatepicker` component because the string of the `id` will be in the `for` attribute in the label tag

### CODE REVIEW

**Comment by talentedandrew** [comment]
@fit how would this be useful, if you can put the label outside of this component also?

**Comment by richvoronov** [comment]
@talentedandrew it's more comfortable and clean when you just use the options

**Comment by richvoronov** [comment]
@talentedandrew another feature is language support! This will be a very simple and useful update for different people from other countries.

If you agree with me I think you should update the "Readme" and describe other interesting features of [moment.js](https://momentjs.com/) library.
For example:

 ```
<ModernDatepicker
   lang="de"
   format={'LL'}
   date={this.state.startDate}
   onChange={(date) => this.handleChange(date)}
 />
```

I'll get:
image

**lang="de"** - change language to German
**format={'LL'}** - change the date format

**Comment by talentedandrew** [comment]
@fit I thinks this will be a good feature to implement. Just give me some time, I will test and merge it ASAP.

**Comment by richvoronov** [comment]
@talentedandrew of course my friend, I will wait for release! 
...But I forgot about the days of the week, the language of the days in the body of calendar does not change when you change the language in the props. Maybe I'll fix it if I have free time

**Comment by talentedandrew** [comment]
@fit thanks :+1:

**Pull request merged**
